### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PassiDel** [PassiDel/accessicity#2]
## Todo
- [ ] Concept
  - [x] main idea
  - [x] ER/Models diagram
  - [x] API routes
  - [x] client routes
  - [ ] Design -> 5.7.
    - [ ] Wireframes
    - [x] Theme
    - [x] CSS Library/Component lib
      - tailwind
- [x] PoC
  - [x] Prisma as ORM
  - [x] Nuxt 3 for SSR
  - [x] JWT as token for auth
  - [x] Pinia as (persistent) storage
  - [x] Switchable darkmode
  - [x] Vue-i18n as i18n lib
    - works with nuxt and vue
    - expandable to many languages
    - remember users language choice, also for SSR
  - [x] leaflet
  	- points
  	- zoom to a point
  	- draw outline
  - [x] convert city data
  	- parse geojson
  	- calculate center point
  	- create db row for each
  	- save table for seeding
- [x] Base
  - [x] API routes (without function)
    - created on server side of nuxt
    - implemented auth and middleware
  - [x] Data Models
    - automatically generated by prisma
  - [x] Pages (without function)
    - create all client side routes
  - [x] Templates
    - create vue components to reuse
    - set up a consistent UI theme
- [ ] Functionality
  - [x] API controller
    - implement all api routes
  - [ ] Pages
    - implement all client routes
- [ ] Test
  - [ ] i18n
    - is everything translated?
  - [ ] A11y
    - colors, meta tags, ARIA label, right ordering
  - [ ] SEO
    - meta, schema.org, open graph
    - consistent colors and branding
  - [ ] Crossbrowser
  - [ ] Legal
    - [ ] Imprint
    - [ ] Data privacy
    - [ ] Cookie banner?
  - [ ] Speed
    - measure using tools like lighthouse or pagespeed
- [x] Deploy
  - [x] Register (sub-)domain
  - [x] Set up nginx as (TLS-)proxy
  - [x] Set up Dockerfile
  - [x] Deploy using docker-compose

### Auth
`POST /login`
Login a user
- email
- password

return
- JWT(?)

`POST /register`
register a new user, check for uniqueness
- name
- email
- password
- [disability]

return
- JWT(?)

### User
`GET /user`
get your own profile, returns
- name
- role
- email
- createdAt
- [disability]
  - isVerified
  - createdAt

`GET /user/:id`
get another users profile, returns
- name
- role
- createdAt
- [disability]
  - isVerified
  - createdAt

`POST /user`
update their own user profile, at least one of:
- name
- password

`POST /user/disability`
update their own disabilities, removes all existing disability if not in list:
- [disability]
  - number (disabilityId)

### Comment
`GET /user/:id/comments?page=:page`
get comments of a user that are public (all comments if `:id == user.id`), paginated, returns list of:
- title
- message
- cityId
- rating
- createdAt
- [disability]
  - rating

### City
`GET /city?page=:page`
get a paginated list of citys:
- id
- name
- loc_lat
- loc_lng
- loc_zoom

`GET /city?minlat&maxlat&minlng&maxlng`
get a list of citys in a bounding box:
- id
- name
- loc_lat
- loc_lng
- loc_zoom
- outline

`GET /city/:id`
get all information about a city with ranking:
- id
- name
- loc_lat
- loc_lng
- loc_zoom
- outline
- [disability]
  - ranking

`GET /city/:id/comments?page=:page`
get all comments, paginated:
- title
- message
- {author}
  - id
  - name
  - [disability]
  - isVerified
- rating
- createdAt
- [disability]
  - rating

`POST /city/:id/comment`
add a new comment to a city
- title
- message
- rating
- [disability]
  - rating

### Disability
`GET /disability`
get all disabilities, returns list of:
- id
- name
- slug
- description
- icon

`GET /disability/:id?page=:page`
get all rankings for every city for one disability, paginated list of:
- {city}
  - id
  - name
- value
